cet_ioctl.c: update the function class_create() due to kernel code change
class_create(const char *name) has no second parameter any more in v6.3-rc1:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dcfbb67e48a2becfce7990386e985b9c45098ee5
And it will cause the cet driver module to fail to compile, as follows:
/root/lkvs/cet/cet_driver/cet_ioctl.c:166:14: error: too many arguments to function ‘class_create’
  166 |         cl = class_create(THIS_MODULE, "char");
So adjust the class_create() function in driver to fix the above problem due
to kernel code change.

Signed-off-by: Pengfei Xu <pengfei.xu@intel.com>