qemu_get_config.py: fix name 'PMU' is not defined issue
If test_params.py doesn't define PMU, qemu_get_config.py will report below
error:
"
NameError: name 'PMU' is not defined
"
Fix this type of error issue.

Signed-off-by: Pengfei Xu <pengfei.xu@intel.com>